Update index.html
gabiprosfriends/tabuada pull request #1
Opened 2023-03-22 10:30 UTC by gabiprosfriends

2023-03-23 16:51 UTC, Adan0k requested changes

2023-03-23 16:51 UTC, Adan0k commented on index.html
> +    <title>tabuada</title>
É um título letra maiuscula pff

2023-03-23 16:51 UTC, Adan0k commented on index.html
> +    <table id="tabuada">
Nomes precisam ser melhores. Esses nomes de ids nao indicam nada sobre o q o elemento representa no caso

2023-03-23 16:51 UTC, Adan0k commented on index.html
> +    <script src="./otherscript.js"></script>
Como falamos, o nome do script tinha que ser mudado posteriormente

2023-03-23 16:51 UTC, Adan0k commented on otherscript.js
> +const table = document.getElementById('tabuada');
Os nomes precisam de ser descritivos do que faz a variável. Imagina sempre que alguem lê o teu código pela primeira vez tem que ter nocao do q a variavel respresenta

2023-03-23 16:51 UTC, Adan0k commented on otherscript.js
> +        const produto = document.createElement("th");
Result e produto é deveras confuso ahhhaaha

2023-03-23 16:51 UTC, Adan0k commented on otherscript.js
> +        const mult = document.createElement("th")
Multiplicador e mult parece q estás a fazer a mesma cena duas vezes

2023-03-23 16:51 UTC, Adan0k commented on script.js
Apaga este ficheiro

2023-03-23 16:51 UTC, Adan0k commented on otherscript.js
> +        const produto = document.createElement("th");
Estes th na vdd devem ser td

2023-03-23 16:51 UTC, Adan0k commented on otherscript.js
> +        line.appendChild(produto);
Podes fazer isto numa linha penso eu

2023-03-23 16:51 UTC, Adan0k commented on style.css
> +body{
Espaco  neste e nos outros

2023-03-23 16:51 UTC, Adan0k commented on style.css
> +    height: 10;
Falta a unidade

2023-03-24 09:36 UTC, Gabriel-Sous-a approved these changes

2023-03-24 09:36 UTC, Gabriel-Sous-a commented on script.js
Doeu um bocado ler isto com os nomes da variaveis em portugues mas tirando isso esta nice

2023-03-24 09:42 UTC, merged